# Generated by Django 3.0.2 on 2020-11-26 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=200)),
                ('CompanyName', models.CharField(max_length=100)),
                ('LoginId', models.CharField(max_length=100)),
                ('Memo', models.CharField(default='', max_length=500)),
                ('Category', models.CharField(max_length=500)),
                ('Rate', models.IntegerField(default=0)),
                ('Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=100)),
                ('EventStart', models.DateTimeField()),
                ('EventEnd', models.DateTimeField()),
                ('Flow', models.BooleanField(default=True)),
                ('Complete', models.BooleanField(default=False)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rikumane_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionTitle', models.CharField(max_length=100)),
                ('TextCounts', models.IntegerField(default=0)),
                ('QuestionContents', models.CharField(default='', max_length=1000)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rikumane_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='files/')),
                ('MemoAnalysis', models.CharField(default='', max_length=4096)),
                ('MemoES', models.CharField(default='', max_length=4096)),
                ('Memo', models.CharField(default='', max_length=4096)),
                ('Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
