# Generated by Django 3.0.8 on 2020-10-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rikumane_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rikumane_app.Account'),
        ),
    ]
