# Generated by Django 3.0.8 on 2020-08-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rikumane_app', '0002_company_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='LoginId',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
