# Generated by Django 3.0.8 on 2020-10-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rikumane_app', '0003_company_loginid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='company',
            new_name='Company',
        ),
    ]
