# Generated by Django 3.0.8 on 2020-10-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rikumane_app', '0004_auto_20201012_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Memo',
            field=models.CharField(default='DUMMY', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionTitle', models.CharField(max_length=100)),
                ('TextCounts', models.IntegerField()),
                ('QuestionContents', models.CharField(max_length=1000)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rikumane_app.Company')),
            ],
        ),
    ]
