# Generated by Django 3.0.8 on 2020-10-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rikumane_app', '0005_auto_20201015_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='LoginId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='URL',
            field=models.URLField(),
        ),
    ]
