# Generated by Django 3.0.8 on 2020-10-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rikumane_app', '0006_auto_20201017_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Memo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
