# Generated by Django 3.0.8 on 2020-10-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rikumane_app', '0007_auto_20201018_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='URL',
            field=models.CharField(max_length=200),
        ),
    ]
