# Generated by Django 3.0.8 on 2020-10-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rikumane_app', '0008_auto_20201018_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Memo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='es',
            name='QuestionContents',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
